# Generated by Django 5.0.7 on 2024-07-14 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ismi')),
            ],
            options={
                'verbose_name': 'Dasturchi',
                'verbose_name_plural': 'Dasturchilar',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ismi')),
            ],
            options={
                'verbose_name': 'Direktor',
                'verbose_name_plural': 'Direktorlar',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=550, verbose_name='Izohi')),
                ('type', models.IntegerField(choices=[(1, 'Kirim'), (2, 'Chiqim')], verbose_name='Turi')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sanasi')),
                ('amount_in_uzs', models.FloatField(blank=True, null=True, verbose_name='Kirim (UZS)')),
                ('amount_in_usd', models.FloatField(blank=True, null=True, verbose_name='Kirim (USD)')),
                ('amount_out_uzs', models.FloatField(blank=True, null=True, verbose_name='Chiqim (UZS)')),
                ('amount_out_usd', models.FloatField(blank=True, null=True, verbose_name='Chiqim (USD)')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.owner', verbose_name='Direktor')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.developer', verbose_name='Dasturchi')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
    ]
