# Generated by Django 5.0.7 on 2024-07-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='worker',
            new_name='dev',
        ),
    ]
