# Generated by Django 5.0.7 on 2024-07-14 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_payment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 7, 14), null=True, verbose_name='Sanasi'),
        ),
    ]
