# Generated by Django 5.0.7 on 2024-07-14 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 14, 8, 49, 39, 3762, tzinfo=datetime.timezone.utc), null=True, verbose_name='Sanasi'),
        ),
    ]
